"""``secdeploy configure --web`` — a tiny local web UI for writing the site config.

Serves ONE SecRouter-themed page (the same palette as the suite's landing page in
``wiring.landing_page_html``) on loopback, with every ``secsite.toml`` option laid out with an
explanation: placement (domain / resources / tier groups), the suite-wide ``[deploy]`` table,
per-resource deploy toggles, declared ``[[users]]``, the ``[secchat.pool]`` options, and the
optional ``[[builds]]`` container builds. Saving round-trips the form through
:meth:`SiteConfig.load`, so the page enforces exactly the same fail-loud validation as the CLI —
errors render inline and nothing is written until the config is valid.

Design notes:

* Pure standard library (``http.server`` + ``urllib.parse``), matching the rest of secdeploy —
  no framework, no CDN, inline CSS/JS only, bound to 127.0.0.1.
* The per-resource/pool/build sections are generated by REFLECTION over the dataclasses
  (:class:`DeployOptions`, :class:`PoolOptions`, :class:`BuildSpec`), with a hand-written help
  text per known field — so a new option added to those classes shows up here automatically
  (with its field name as a placeholder explanation until help is written).
* Validation is a round trip: form → TOML text → ``SiteConfig.load`` → on error, re-render the
  form with the submitted values + the errors; on success, write the destination (or a named
  profile — see ``sites/``) and show the saved banner.
"""

from __future__ import annotations

import dataclasses
import html
import json
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs

from .manifest import Manifest
from .site import (
    BuildSpec,
    DeployOptions,
    PoolOptions,
    SiteConfig,
    site_profile_path,
)

DEFAULT_PORT = 4477

# Tiers, mirroring configure.py's wizard order.
TIERS = ["identity", "inference", "gateway", "collab", "edge"]

# One-line explanations per field, keyed "<section>.<field>". A field with no entry still renders
# (reflection) — it just shows its name until help is written here.
HELP: dict[str, str] = {
    "site.domain": "The suite's internal DNS domain — every service gets <name>.<domain> (e.g. secchat.sec.internal).",
    "site.upstream_dns": "Comma-separated resolvers SecDNS forwards non-suite queries to (e.g. 1.1.1.1, 8.8.8.8).",
    "deploy.without": "Optional components to DROP — check what you already run elsewhere (your own CA, IdP, …).",
    "deploy.ssh": "Control-host mode: push deploys to each resource over SSH instead of deploying locally.",
    "resource.name": "Short resource id (e.g. mac, core, gpu1) — referenced by the tier placement below.",
    "resource.target": "Deploy target for this host: macos (compose via Colima) or fedora-fips (hardened systemd).",
    "resource.address": "The host's address as OTHER resources reach it (an IP or resolvable name).",
    "resource.capabilities": "Comma-separated capability tags (e.g. fips, gpu) — informational placement hints.",
    "resource.with_inference": "Stand up SecLLM (local model serving) on this host.",
    "resource.inference_backend": "SecLLM backend on macOS: auto (mlx if installed), mlx, metal (vLLM-Metal — serves archs mlx can't), vllm, or mock.",
    "resource.autostart_models": "Comma-separated SecLLM catalog ids to load at boot (e.g. fast, balanced) instead of on first request.",
    "resource.with_agent": "Install the secagent pi harness + wire the developer's pi onboarding on this host.",
    "resource.configure_resolver": "Point this host's OS resolver at SecDNS for the suite domain (macOS /etc/resolver).",
    "resource.tls": "macOS: obtain a SecCert TLS certificate for host-side services.",
    "resource.configure_hosts": "macOS: map host.docker.internal in /etc/hosts so host-side clients use the cert's hostname.",
    "resource.trust_ca": "macOS: add the SecCert CA to the system keychain so browsers trust the suite.",
    "resource.model_dir": "Air-gapped model snapshots directory (pre-downloaded weights) — blank = download on demand.",
    "users.username": "Login name provisioned in SecSSO with a random initial password (printed once at deploy; reset forced on first login).",
    "users.email": "The account's email claim.",
    "users.name": "Display name.",
    "users.groups": "Comma-separated groups (created if absent) — match SecRouter's security.policy.groups for per-group budgets.",
    "pool.enabled": "Run coding agents in server-launched Kubernetes pods (the agent pool).",
    "pool.image": "The runnerd image the pods run — build it via [[builds]] below, or set build_image.",
    "pool.namespace": "Namespace the agent pods run in.",
    "pool.service_account": "SecChat's ServiceAccount (the RoleBinding subject that may create/delete pool pods).",
    "pool.service_account_namespace": "Namespace that ServiceAccount lives in.",
    "pool.git_host": "The enclave git host pods may reach — surfaced on the egress NetworkPolicy for FQDN-aware CNIs.",
    "pool.secchat_url": "URL a pod dials BACK to SecChat (/runner + /agent-llm) — must be reachable from inside the cluster.",
    "pool.api_server": "Out-of-cluster SecChat: the Kubernetes API URL reachable from the SecChat CONTAINER (must be in the API cert's SANs).",
    "pool.create_service_account": "Out-of-cluster SecChat: also create the SA + token Secret, extract the credential, and mount it into the compose service.",
    "pool.cpu": "Per-pod CPU limit (K8s quantity, e.g. 1 or 500m).",
    "pool.memory": "Per-pod memory limit (e.g. 1Gi).",
    "pool.max_pods": "Global cap on concurrent pool pods (ResourceQuota + SecChat's own admission).",
    "pool.max_per_owner": "Per-user cap on concurrent pool pods.",
    "pool.ttl_seconds": "Hard pod TTL (activeDeadlineSeconds) — the reap backstop.",
    "pool.build_image": "Build Dockerfile.runnerd from the fetched secchat checkout and push it (requires registry).",
    "pool.registry": "Registry to push the runnerd image to (required when build_image; leave blank for local-only images).",
    "pool.apply": "kubectl-apply the emitted pool manifests during deploy (else they're written for you to apply).",
    "pool.kube_context": "kubectl --context for apply/extraction (e.g. colima).",
    "pool.analysis_images": "Analysis sidecar catalog, one name=image per line — attachable to an agent's pod, sharing its /workspace.",
    "builds.name": "Image name — built as <name>:<tag>.",
    "builds.component": "Which fetched component checkout is the build context (e.g. secchat, secagent).",
    "builds.dockerfile": "Dockerfile path, relative to that checkout.",
    "builds.tag": "Image tag (default local — right for colima/k3s shared-runtime clusters, no registry needed).",
    "builds.context": "Build context, relative to the checkout (default .).",
    "builds.push": "Push <registry>/<name>:<tag> after building (registry required).",
    "builds.registry": "Registry to push to (only with push).",
    "builds.platform": "Optional --platform (e.g. linux/arm64).",
    "save.dest": "Where to save: blank = the destination this server was started with; a bare name = the sites/<name>.toml profile (select later with --site <name>).",
}


def _esc(s: object) -> str:
    return html.escape(str(s), quote=True)


def _help(key: str) -> str:
    return HELP.get(key, key.rsplit(".", 1)[-1].replace("_", " "))


def _input(name: str, value: object, help_key: str, kind: str = "text") -> str:
    """One labeled form control with its explanation line."""
    label = help_key.rsplit(".", 1)[-1].replace("_", " ")
    if kind == "bool":
        checked = " checked" if value else ""
        control = (f'<label class="chk"><input type="checkbox" name="{_esc(name)}"{checked}> '
                   f"{_esc(label)}</label>")
        return f'<div class="field">{control}<p class="help">{_esc(_help(help_key))}</p></div>'
    if kind == "number":
        control = f'<input type="number" name="{_esc(name)}" value="{_esc(value)}">'
    elif kind == "textarea":
        control = f'<textarea name="{_esc(name)}" rows="3">{_esc(value)}</textarea>'
    else:
        control = f'<input type="text" name="{_esc(name)}" value="{_esc(value)}">'
    return (f'<div class="field"><label>{_esc(label)}</label>{control}'
            f'<p class="help">{_esc(_help(help_key))}</p></div>')


def _widget_kind(f: dataclasses.Field) -> str:
    if f.type in ("bool", bool):
        return "bool"
    if f.type in ("int", int):
        return "number"
    return "text"


def _dataclass_fields(obj, section: str, prefix: str, skip: set[str] | None = None) -> str:
    """Reflection-driven controls for every field of a dataclass instance. Dict fields render as
    a name=image-per-line textarea; list[str] fields as comma-joined text."""
    out: list[str] = []
    for f in dataclasses.fields(obj):
        if skip and f.name in skip:
            continue
        value = getattr(obj, f.name)
        key = f"{section}.{f.name}"
        name = f"{prefix}{f.name}"
        if isinstance(value, dict):
            text = "\n".join(f"{k}={v}" for k, v in sorted(value.items()))
            out.append(_input(name, text, key, "textarea"))
        elif isinstance(value, list):
            out.append(_input(name, ", ".join(str(v) for v in value), key))
        elif isinstance(value, bool):
            out.append(_input(name, value, key, "bool"))
        elif isinstance(value, int):
            out.append(_input(name, value, key, "number"))
        else:
            out.append(_input(name, value, key))
    return "\n".join(out)


CSS = """
:root {
  --mono: ui-monospace, "SF Mono", SFMono-Regular, Menlo, Consolas, monospace;
  --sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --bg:#e7e3d8; --panel:#f3f0e8; --panel2:#fbfaf4; --fg:#211f18; --muted:#6c6552;
  --accent:#4f6a2e; --accent-ink:#f6f3ea; --border:#cdc6b2; --rule:#dad4c2;
  --shadow:2px 2px 0 rgba(33,31,24,.06); --bad:#8a3b2e; --bad-bg:#f2e2de;
}
@media (prefers-color-scheme: dark) { :root {
  --bg:#171511; --panel:#201e17; --panel2:#29271e; --fg:#e8e3d3; --muted:#9a9077;
  --accent:#94ad50; --accent-ink:#16140e; --border:#3a3730; --rule:#272520;
  --shadow:2px 2px 0 rgba(0,0,0,.30); --bad:#c96a5a; --bad-bg:#33211d;
}}
* { box-sizing:border-box; }
body { margin:0; font:14px/1.55 var(--sans); background:var(--bg); color:var(--fg);
       background-image:linear-gradient(var(--rule) 1px, transparent 1px);
       background-size:100% 28px; background-attachment:fixed; }
header { display:flex; align-items:baseline; gap:12px; padding:14px 22px; background:var(--panel);
         border-bottom:1px solid var(--border); position:sticky; top:0; z-index:2; }
header h1 { margin:0; font:700 16px var(--mono); }
header .sub { color:var(--muted); font:12px var(--mono); }
main { max-width: 880px; margin: 24px auto 80px; padding: 0 18px; }
section.card { background:var(--panel); border:1px solid var(--border); border-radius:2px;
               box-shadow:var(--shadow); margin-bottom:22px; padding:16px 18px; }
section.card > h2 { margin:0 0 4px; font:700 13px var(--mono); letter-spacing:.6px;
                    text-transform:uppercase; color:var(--accent); }
section.card > p.blurb { margin:0 0 12px; color:var(--muted); font-size:12.5px; }
.field { margin: 10px 0; }
.field label { display:block; font:600 12.5px var(--sans); margin-bottom:3px; }
.field input[type=text], .field input[type=number], .field select, .field textarea {
  width:100%; padding:7px 9px; font:13px var(--mono); color:var(--fg);
  background:var(--panel2); border:1px solid var(--border); border-radius:2px; }
.field .help { margin:3px 0 0; font-size:11.5px; color:var(--muted); }
.field label.chk { display:flex; gap:8px; align-items:center; font:600 13px var(--sans); }
.row { border:1px dashed var(--border); border-radius:2px; padding:10px 12px; margin:10px 0;
       background:var(--panel2); }
.row .rowhead { display:flex; justify-content:space-between; align-items:center; }
.row .rowhead b { font:700 12px var(--mono); color:var(--muted); }
button, .btn { font:600 13px var(--sans); padding:8px 14px; border-radius:2px; cursor:pointer;
               border:1px solid var(--border); background:var(--panel2); color:var(--fg); }
button.primary { background:var(--accent); color:var(--accent-ink); border-color:var(--accent); }
button.small { padding:3px 9px; font-size:12px; }
.errors { background:var(--bad-bg); border:1px solid var(--bad); color:var(--bad);
          border-radius:2px; padding:10px 14px; margin-bottom:18px; font:12.5px var(--mono);
          white-space:pre-wrap; }
.saved { background:var(--panel); border:1px solid var(--accent); color:var(--accent);
         border-radius:2px; padding:10px 14px; margin-bottom:18px; font:600 13px var(--mono); }
.savebar { position:sticky; bottom:0; background:var(--panel); border-top:1px solid var(--border);
           padding:12px 18px; display:flex; gap:12px; align-items:center; }
.savebar input { flex:1; padding:7px 9px; font:13px var(--mono); background:var(--panel2);
                 border:1px solid var(--border); border-radius:2px; color:var(--fg); }
"""

JS = """
function addRow(listId, tplId) {
  const list = document.getElementById(listId);
  const tpl = document.getElementById(tplId);
  const idx = list.querySelectorAll('.row').length;
  const div = document.createElement('div');
  div.className = 'row';
  div.innerHTML = tpl.innerHTML.replaceAll('__I__', String(idx));
  list.appendChild(div);
}
function rmRow(btn) { btn.closest('.row').remove(); }
"""


def _section(title: str, blurb: str, body: str) -> str:
    return (f'<section class="card"><h2>{_esc(title)}</h2>'
            f'<p class="blurb">{_esc(blurb)}</p>{body}</section>')


def _resource_row(idx: object, name: str = "", target: str = "macos", address: str = "",
                  capabilities: str = "", opts: DeployOptions | None = None) -> str:
    opts = opts or DeployOptions()
    pre = f"res.{idx}."
    targets = "".join(
        f'<option value="{t}"{" selected" if t == target else ""}>{t}</option>'
        for t in ("macos", "fedora-fips"))
    head = ('<div class="rowhead"><b>resource</b>'
            '<button type="button" class="small" onclick="rmRow(this)">remove</button></div>')
    placement = (
        _input(pre + "name", name, "resource.name")
        + f'<div class="field"><label>target</label><select name="{pre}target">{targets}</select>'
          f'<p class="help">{_esc(_help("resource.target"))}</p></div>'
        + _input(pre + "address", address, "resource.address")
        + _input(pre + "capabilities", capabilities, "resource.capabilities")
    )
    return f'<div class="row">{head}{placement}{_dataclass_fields(opts, "resource", pre)}</div>'


def _user_row(idx: object, username: str = "", email: str = "", name: str = "",
              groups: str = "") -> str:
    pre = f"user.{idx}."
    head = ('<div class="rowhead"><b>user</b>'
            '<button type="button" class="small" onclick="rmRow(this)">remove</button></div>')
    return ('<div class="row">' + head
            + _input(pre + "username", username, "users.username")
            + _input(pre + "email", email, "users.email")
            + _input(pre + "name", name, "users.name")
            + _input(pre + "groups", groups, "users.groups")
            + "</div>")


def _build_row(idx: object, spec: BuildSpec | None = None) -> str:
    spec = spec or BuildSpec()
    pre = f"build.{idx}."
    head = ('<div class="rowhead"><b>build</b>'
            '<button type="button" class="small" onclick="rmRow(this)">remove</button></div>')
    return f'<div class="row">{head}{_dataclass_fields(spec, "builds", pre)}</div>'


def render_form(site: SiteConfig, manifest: Manifest, dest: str,
                errors: list[str] | None = None, saved: str | None = None) -> str:
    """The whole page, prefilled from ``site``."""
    topo = site.topology
    banner = ""
    if errors:
        banner = f'<div class="errors">{_esc(chr(10).join(errors))}</div>'
    elif saved:
        banner = f'<div class="saved">✓ saved → {_esc(saved)}</div>'

    site_sec = _section("Site", "The suite's identity — every component is addressed inside this domain.",
                        _input("domain", topo.domain, "site.domain")
                        + _input("upstream_dns", ", ".join(topo.upstream_dns), "site.upstream_dns"))

    res_rows = "".join(
        _resource_row(i, r.name, r.target, r.address, ", ".join(r.capabilities),
                      site.deploy_for(r.name))
        for i, r in enumerate(topo.resources.values()))
    res_sec = _section(
        "Resources", "The machines the suite runs on, each with its per-host deploy toggles.",
        f'<div id="resources">{res_rows}</div>'
        '<button type="button" onclick="addRow(\'resources\',\'res-tpl\')">+ add resource</button>')

    tier_fields = "".join(
        _input(f"group.{tier}", ", ".join(topo.groups.get(tier, [])), "site.groups")
        .replace("<label>groups</label>", f"<label>{tier}</label>")
        .replace(_esc(_help("site.groups")),
                 _esc(f"Which resource(s) host the {tier} tier (comma-separated for a spread tier)."))
        for tier in TIERS)
    tier_sec = _section("Tier placement", "Which resource hosts each suite tier.", tier_fields)

    optional = manifest.optionals()
    without_boxes = "".join(
        f'<label class="chk"><input type="checkbox" name="without" value="{_esc(c)}"'
        f'{" checked" if c in site.without else ""}> {_esc(c)}</label>'
        for c in optional)
    deploy_sec = _section(
        "Suite deploy options", _help("deploy.without"),
        f'<div class="field">{without_boxes}<p class="help">{_esc(_help("deploy.without"))}</p></div>'
        + _input("ssh", site.ssh, "deploy.ssh", "bool"))

    user_rows = "".join(
        _user_row(i, u.username, u.email, u.name, ", ".join(u.groups))
        for i, u in enumerate(site.users))
    users_sec = _section(
        "Users", "Accounts SecDeploy provisions in SecSSO (random initial password, reset forced).",
        f'<div id="users">{user_rows}</div>'
        '<button type="button" onclick="addRow(\'users\',\'user-tpl\')">+ add user</button>')

    pool_sec = _section(
        "Agent pool (Kubernetes)",
        "Coding agents in server-launched, per-session pods. Leave disabled without a cluster.",
        _dataclass_fields(site.secchat_pool, "pool", "pool."))

    build_rows = "".join(_build_row(i, b) for i, b in enumerate(site.builds))
    builds_sec = _section(
        "Container builds", "Images the deploy builds from fetched component checkouts.",
        f'<div id="builds">{build_rows}</div>'
        '<button type="button" onclick="addRow(\'builds\',\'build-tpl\')">+ add build</button>')

    templates = (
        f'<template id="res-tpl">{_resource_row("__I__")}</template>'
        f'<template id="user-tpl">{_user_row("__I__")}</template>'
        f'<template id="build-tpl">{_build_row("__I__")}</template>')

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>secdeploy configure</title><style>{CSS}</style></head>
<body>
<header><h1>secdeploy configure</h1><span class="sub">SecRouter Suite — site configuration</span></header>
<main>
{banner}
<form method="post" action="/save">
{site_sec}{res_sec}{tier_sec}{deploy_sec}{users_sec}{pool_sec}{builds_sec}
<div class="savebar">
  <input type="text" name="save_as" placeholder="save as… (blank = {_esc(dest)}; a bare name = sites/&lt;name&gt;.toml)">
  <button class="primary" type="submit">Validate &amp; save</button>
</div>
</form>
{templates}
<script>{JS}</script>
</main></body></html>"""


# ── form → TOML → SiteConfig ───────────────────────────────────────────────────────────────────

def _rows(form: dict[str, list[str]], prefix: str) -> list[dict[str, str]]:
    """Collect indexed row fields (`res.0.name`, `res.0.address`, …) into per-row dicts, in index
    order, skipping rows whose every value is blank (a removed/empty template row)."""
    rows: dict[int, dict[str, str]] = {}
    for key, values in form.items():
        parts = key.split(".", 2)
        if len(parts) != 3 or parts[0] != prefix or not parts[1].isdigit():
            continue
        rows.setdefault(int(parts[1]), {})[parts[2]] = values[0]
    out = []
    for idx in sorted(rows):
        if any(v.strip() for v in rows[idx].values()):
            out.append(rows[idx])
    return out


def _toml_str(v: str) -> str:
    return json.dumps(v)  # JSON string escaping is valid TOML for our ASCII-ish config values


def _toml_list(csv: str) -> str:
    items = [i.strip() for i in csv.split(",") if i.strip()]
    return "[" + ", ".join(_toml_str(i) for i in items) + "]"


def form_to_toml(form: dict[str, list[str]]) -> str:
    """Assemble the submitted form into secsite.toml text (validated separately via
    SiteConfig.load — this only SHAPES the data)."""

    def val(key: str, default: str = "") -> str:
        return form.get(key, [default])[0].strip()

    def flag(key: str) -> bool:
        return key in form  # checkboxes submit only when checked

    lines: list[str] = [f"domain = {_toml_str(val('domain'))}"]
    if val("upstream_dns"):
        lines.append(f"upstream_dns = {_toml_list(val('upstream_dns'))}")
    without = [v for v in form.get("without", [])]
    lines += ["", "[deploy]"]
    if without:
        lines.append("without = [" + ", ".join(_toml_str(w) for w in without) + "]")
    if flag("ssh"):
        lines.append("ssh = true")

    bool_res_keys = {"with_inference", "with_agent", "configure_resolver", "tls",
                     "configure_hosts", "trust_ca"}
    for row in _rows(form, "res"):
        name = row.get("name", "").strip()
        lines += ["", f"[resources.{name}]"]
        lines.append(f"target = {_toml_str(row.get('target', 'macos'))}")
        lines.append(f"address = {_toml_str(row.get('address', ''))}")
        if row.get("capabilities", "").strip():
            lines.append(f"capabilities = {_toml_list(row['capabilities'])}")
        for k in sorted(bool_res_keys):
            if row.get(k):  # checkbox present = on
                lines.append(f"{k} = true")
        if row.get("model_dir", "").strip():
            lines.append(f"model_dir = {_toml_str(row['model_dir'].strip())}")
        if row.get("autostart_models", "").strip():
            lines.append(f"autostart_models = {_toml_list(row['autostart_models'])}")
        backend = row.get("inference_backend", "").strip()
        if backend and backend != "auto":
            lines.append(f"inference_backend = {_toml_str(backend)}")

    for tier in TIERS:
        targets = val(f"group.{tier}")
        if targets:
            names = [t.strip() for t in targets.split(",") if t.strip()]
            lines += ["", f"[groups.{tier}]"]
            if len(names) == 1:
                lines.append(f"resource = {_toml_str(names[0])}")
            else:
                lines.append("resources = [" + ", ".join(_toml_str(n) for n in names) + "]")

    for row in _rows(form, "user"):
        lines += ["", "[[users]]"]
        lines.append(f"username = {_toml_str(row.get('username', '').strip())}")
        lines.append(f"email = {_toml_str(row.get('email', '').strip())}")
        lines.append(f"name = {_toml_str(row.get('name', '').strip())}")
        lines.append(f"groups = {_toml_list(row.get('groups', ''))}")

    if flag("pool.enabled"):
        lines += ["", "[secchat.pool]", "enabled = true"]
        analysis_lines: list[str] = []
        for f in dataclasses.fields(PoolOptions):
            if f.name == "enabled":
                continue
            key = f"pool.{f.name}"
            if f.name == "analysis_images":
                for entry in val(key).splitlines():
                    if "=" in entry:
                        n, _, img = entry.partition("=")
                        if n.strip() and img.strip():
                            analysis_lines.append(f"{n.strip()} = {_toml_str(img.strip())}")
                continue
            if _widget_kind(f) == "bool":
                if flag(key):
                    lines.append(f"{f.name} = true")
            elif _widget_kind(f) == "number":
                if val(key):
                    lines.append(f"{f.name} = {int(val(key))}")
            elif val(key):
                lines.append(f"{f.name} = {_toml_str(val(key))}")
        if analysis_lines:
            lines += ["", "[secchat.pool.analysis_images]", *analysis_lines]

    for row in _rows(form, "build"):
        lines += ["", "[[builds]]"]
        for f in dataclasses.fields(BuildSpec):
            v = row.get(f.name, "")
            if _widget_kind(f) == "bool":
                if v:
                    lines.append(f"{f.name} = true")
            elif v.strip():
                lines.append(f"{f.name} = {_toml_str(v.strip())}")

    return "\n".join(lines) + "\n"


def validate_form(form: dict[str, list[str]], manifest: Manifest,
                  tmp_dir: Path) -> tuple[SiteConfig | None, str, list[str]]:
    """form → TOML → SiteConfig.load. Returns (site|None, toml_text, errors) — the SAME fail-loud
    validation the CLI applies, surfaced back onto the page."""
    text = form_to_toml(form)
    tmp = tmp_dir / "webconfig-candidate.toml"
    tmp.write_text(text)
    try:
        return SiteConfig.load(tmp, manifest), text, []
    except ValueError as exc:
        return None, text, str(exc).splitlines()
    finally:
        tmp.unlink(missing_ok=True)


# ── the server ─────────────────────────────────────────────────────────────────────────────────

def serve(manifest: Manifest, dest: str, port: int = DEFAULT_PORT,
          open_browser: bool = True) -> None:
    """Serve the configurator on 127.0.0.1:``port`` until interrupted. GET / renders the form
    (prefilled from ``dest`` when it loads); POST /save validates + writes."""
    import tempfile

    dest_path = Path(dest)

    def initial_site() -> SiteConfig:
        if dest_path.exists():
            try:
                return SiteConfig.load(dest_path, manifest)
            except ValueError:
                pass  # unparseable current file — start from a blank form rather than crash
        return SiteConfig.single_host(manifest, "macos")

    class Handler(BaseHTTPRequestHandler):
        def _page(self, body: str, status: int = 200) -> None:
            data = body.encode()
            self.send_response(status)
            self.send_header("content-type", "text/html; charset=utf-8")
            self.send_header("content-length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def do_GET(self):
            if self.path not in ("/", "/index.html"):
                self.send_response(404)
                self.end_headers()
                return
            self._page(render_form(initial_site(), manifest, dest))

        def do_POST(self):
            if self.path != "/save":
                self.send_response(404)
                self.end_headers()
                return
            length = int(self.headers.get("content-length", "0"))
            form = parse_qs(self.rfile.read(length).decode(), keep_blank_values=True)
            with tempfile.TemporaryDirectory() as td:
                site, text, errors = validate_form(form, manifest, Path(td))
            if errors:
                self._page(render_form(initial_site(), manifest, dest, errors=errors), 422)
                return
            save_as = form.get("save_as", [""])[0].strip()
            target = site_profile_path(save_as) if save_as and "/" not in save_as else \
                Path(save_as) if save_as else dest_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
            self._page(render_form(site, manifest, dest, saved=str(target)))  # type: ignore[arg-type]

        def log_message(self, *args):  # quiet — this is a local tool, not a service
            pass

    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    url = f"http://127.0.0.1:{port}/"
    print(f"secdeploy configure --web: {url}  (Ctrl-C to stop)")
    if open_browser:
        threading.Timer(0.3, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped")
    finally:
        server.server_close()
