"""Topology-driven deploy wiring — the bridge from the site topology to the targets.

This module turns a :class:`~secdeploy.topology.Topology` into the concrete things a deploy
needs: *which resource am I*, *which components run here*, and the **addressing artifacts** —
the ``secdns`` zone file and the per-component peer-URL env files. It is deliberately free of
any target/OS specifics so it can be unit-tested and reused by every target.

Backward compatibility: when no ``topology.toml`` exists, :func:`active_topology` synthesizes
a single-host topology (everything on this box, addresses at loopback), so a plain
``secdeploy deploy macos`` behaves exactly as it did before topologies existed.
"""

from __future__ import annotations

from pathlib import Path

from .manifest import Manifest
from .topology import Topology


def active_topology(
    manifest: Manifest,
    topology_path: str | Path,
    target: str,
    address: str = "127.0.0.1",
) -> tuple[Topology, bool]:
    """Return ``(topology, from_file)``.

    Loads ``topology_path`` if it exists; otherwise synthesizes a single-host topology on
    ``target`` (reproducing the pre-topology, everything-on-this-host behavior).
    """
    path = Path(topology_path)
    if path.exists():
        return Topology.load(path, manifest), True
    return Topology.single_host(manifest, target, address=address), False


def resource_for(topology: Topology, target: str, explicit: str | None = None) -> str:
    """Pick which resource this invocation acts on.

    ``--resource`` wins; else the unique resource whose ``target`` matches; else, if there is
    only one resource, that one; else an error listing the candidates.
    """
    if explicit:
        if explicit not in topology.resources:
            raise KeyError(
                f"unknown resource {explicit!r}; defined: {', '.join(topology.resources) or '(none)'}"
            )
        return explicit
    matches = [name for name, r in topology.resources.items() if r.target == target]
    if len(matches) == 1:
        return matches[0]
    if len(topology.resources) == 1:
        return next(iter(topology.resources))
    candidates = ", ".join(matches or topology.resources)
    raise ValueError(
        f"could not pick a resource for target {target!r} — candidates: {candidates}. "
        f"Pass --resource <name>."
    )


def _short(fqdn: str, domain: str) -> str:
    suffix = "." + domain
    return fqdn[: -len(suffix)] if fqdn.endswith(suffix) else fqdn


def zone_text(topology: Topology, without: list[str] | None = None) -> str:
    """Render the whole-suite ``secdns`` zone file (one A record per placed component).

    The zone is suite-wide (not per-resource): a host must be able to resolve peers that live
    on *other* hosts, and secdns — wherever it runs — serves them all.
    """
    lines = [
        f"# secdns zone for {topology.domain}",
        "# generated by secdeploy from the site topology — edit topology.toml, not this file",
    ]
    for fqdn, rtype, addr in topology.zone(without):
        lines.append(f"{_short(fqdn, topology.domain):<28} {rtype:<5} {addr}")
    return "\n".join(lines) + "\n"


def env_text(topology: Topology, component: str, without: list[str] | None = None) -> str:
    """Render one component's peer-wiring env file (``SEC_DOMAIN``, ``SELF_*``, ``<PEER>_URL``)."""
    env = topology.env_for(component, without)
    lines = [f"# {component} peer wiring — generated by secdeploy from the site topology"]
    lines += [f"{k}={v}" for k, v in env.items()]
    return "\n".join(lines) + "\n"


def secdns_env_text(topology: Topology, zone_path: str) -> str:
    """Render the ``secdns`` service env (domain / upstream / zone) from the topology."""
    return (
        "# secdns — generated by secdeploy from the site topology\n"
        f"SECDNS_DOMAIN={topology.domain}\n"
        f"SECDNS_ZONE={zone_path}\n"
        f"SECDNS_UPSTREAM={','.join(topology.upstream_dns)}\n"
        "SECDNS_PORT=53\n"
        "SECDNS_ADMIN_BIND=127.0.0.1\n"
        "SECDNS_ADMIN_PORT=47053\n"
    )


def write_addressing(
    topology: Topology,
    out_dir: str | Path,
    resource: str,
    without: list[str] | None = None,
) -> dict[str, object]:
    """Write the addressing artifacts for ``resource`` into ``out_dir``.

    Produces ``<out_dir>/secdns.zone`` (the suite-wide zone) and ``<out_dir>/env/<c>.env`` for
    every component placed on ``resource``. Returns the written paths.
    """
    rdir = Path(out_dir)
    (rdir / "env").mkdir(parents=True, exist_ok=True)
    zone_path = rdir / "secdns.zone"
    zone_path.write_text(zone_text(topology, without))
    env_paths: dict[str, Path] = {}
    for name in topology.components_on(resource, without):
        ep = rdir / "env" / f"{name}.env"
        ep.write_text(env_text(topology, name, without))
        env_paths[name] = ep
    return {"zone": zone_path, "env": env_paths}
